### ISSUE TITLE
Unable to resolve primitive values for mocks

### ISSUE THREAD

**Issue by hunter-horton** [moq/Moq.AutoMocker#123]
I am running into an issue where I am unable to setup a mock using AutoMocker when the constructor takes in primitive values. For instance, if I want to setup a mock and it takes in a `string` in the constructor an exception is thrown. I would expect that `default` would be provided instead of trying to mock it. 

That being said, I love the project and use it in all of my repos! Has definitely increased my productivity, with this edge case being the only thing that has caused me any issues. Thanks for all the hard work!

**Comment by Keboo** [comment]
Hi @hunter-horton 
Glad to hear you have found this library useful. 
Automatically inserting primitive values is something we have thrown around a bit, and have not come up with great answers for. There are a few things to consider. First Moq itself requires you to explicitly pass arguments to Mock<T>'s constructor to handle constructors that take in parameters. Second simply inserting default may not be right in all cases. Especially with string this starts to get a little interesting with [nullable reference types](https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references); should it insert empty string with nullable reference types enabled. Currently my thinking is that this problem is best solved in each individual project so that people can decide which method they like.

Within this library there a built-in way to let you handle these cases. The `Use` method lets you inject a value into `AutoMocker` that it will use when resolving parameters.
Something like this:
```C#
[TestMethod]
[Description("Issue 123")]
public void It_creates_mock_for_type_with_primitive_type_ctor_parameter()
{
    AutoMocker mocker = new();
    mocker.Use("");
    Mock<HasStringParameter> mock = mocker.GetMock<HasStringParameter>();
    Assert.IsTrue(string.IsNullOrEmpty(mock.Object.String));
}

public class HasStringParameter
{
    public HasStringParameter(string @string)
    {
        String = @string;
    }

    public string String { get; }
}
```

**Comment by Keboo** [comment]
Closing for now, Opened #138 with unit tests showing how this can be done with the `Use` or a custom resolver.
