### ISSUE TITLE
Why no release in the last year?

### ISSUE THREAD

**Issue by johnknoop** [moq/Moq.AutoMocker#280]
I would need the `InstanceResolver` added by [this PR](https://github.com/moq/Moq.AutoMocker/pull/237). But no new release has been made since it was merged. How come?

**Comment by Keboo** [comment]
Mostly because during most of the year there were not that many updates. We have recently started back in adding additional features/fixes so another release is in progress. We did have an issue with the preview nugets not going out due to the ApiKey being expired, that has now been corrected and you will see a preview package out there (https://www.nuget.org/packages/Moq.AutoMock/3.6.0-ci0532).

**Comment by johnknoop** [comment]
Thanks!
